package fr.theialand.insitu.dataportal.api.scanr;

import org.springframework.context.annotation.ComponentScan;


/**
 * ComponentScan needed to scan the class generated by the codegen
 */
@ComponentScan
public class ScanRConfig  {

}
